version: '3.8'

services:
  php: &default-php
    tty: true
    build: &default-php-build
      context: .
      dockerfile: Dockerfile
      args:
        version: cli
    volumes:
      - ./src:/var/www/src
      - ./tests:/var/www/tests
      - ./phpunit.xml:/var/www/phpunit.xml
  php-8.1:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 8.1-cli
  php-8.2:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 8.2-cli
  php-8.3:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 8.3-cli
  php-8.4:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 8.4.0RC3-cli-bookworm
  couchbase:
    build:
      context: .
      dockerfile: docker/Dockerfile-Couchbase
    healthcheck:
      test: ["CMD", "curl", "-f", "http://Administrator:password@localhost:8091/pools/default/buckets/default"]
      interval: 1s
      timeout: 3s
      retries: 60
  memcached:
    image: memcached
    # not sure how to properly healthcheck
  mysql:
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=cache
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hmysql", "-P3306", "-uuser", "-ppass"]
      interval: 3s
      timeout: 3s
      retries: 30
  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=cache
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 3s
      timeout: 3s
      retries: 30
  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 30
